version: '3.4'

services:
  sample.socialmedia.useractivity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  kafkaserver:
    image: "spotify/kafka:latest"
    ports:
      - 2181
      - 9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  
  mongo-express:
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        - ME_CONFIG_MONGODB_AUTH_USERNAME=root
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    depends_on:
        - mongodb
    ports:
      - "8081"
